[package]
name = "one_bridge_canister"
description = "A Fully On-Chain Multi-Chain Token Bridge for the Internet Computer, Ethereum, BNB Chain and other EVM chains."
publish = false
repository = "https://github.com/ldclabs/ic-one-bridge/tree/main/src/one_bridge_canister"
version.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
candid = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-cdk-management-canister = { workspace = true }
ic-stable-structures = { workspace = true }
ic-http-certification = { workspace = true }
ic_auth_types = { workspace = true }
ic-secp256k1 = { workspace = true }
ic-ed25519 = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
solana-hash = { workspace = true }
solana-pubkey = { workspace = true, features = ["curve25519"] }
solana-transaction = { workspace = true, features = ["serde"] }
solana-instruction = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
ic-dummy-getrandom-for-wasm = { workspace = true }

[dev-dependencies]
futures = { workspace = true, features = ["executor"] }
